### ISSUE TITLE
do not apply imagesdir

### ISSUE THREAD

**Issue by igagis** [asciidoctor/asciidoctor-mathematical#8] opened 2016-05-31 14:53 UTC
the line
```
image_target_dir = document.attr 'imagesoutdir', (document.attr 'imagesdir')
```
should not use imagesdir because the image was generated to imagesoutdir only.
So, if document has both
```
:imagesdir: tmp
:imagesoutdir: tmp
```

the image is saved to tmp, but resulting document refers to tmp/tmp and does not find the image

**Comment by mojavelinux** [comment] 2016-08-14 02:44
What I recommend is studying what Asciidoctor Diagram does. It would be very nice if Asciidoctor Mathematical and Asciidoctor Diagram handled image generation in the same way. That will be least surprising for users.

Please refer to https://github.com/asciidoctor/asciidoctor-diagram/blob/v1.5.1/lib/asciidoctor-diagram/extensions.rb#L145-L205

**Comment by paulvickers** [comment] 2016-08-15 13:48
Agreed. I can't reconcile the images folder when generating an HTML file. It has been recommended to use:

    :imagesdir: images
    :imagesoutdir: .

but that seems to just put the SVG files in the root, rather than in `images` which is where the HTML page looks for them.

**Comment by ProgramFan** [comment] 2016-08-15 23:42
I will investigate into this issue this weekend, hopefully.

**Comment by mojavelinux** [comment] 2016-08-16 00:19
Great! If you need advice, don't hesitate to post questions here. I'm on the thread.

**Comment by paulvickers** [comment] 2016-08-16 15:15
I also discovered that seemingly regardless of what `:images:` and `:imagesoutdir:` are set to
any *inline* stem pngs get put into the `images` folder, but all *block* stem pngs get put into `.`.

**Comment by mojavelinux** [comment] 2016-08-16 21:18
I didn't think that inline stem macros were supported yet.

**Comment by mojavelinux** [comment] 2016-08-17 06:17
My mistake. The extension supports inline stem via a preprocessor. I missed that.

**Comment by mojavelinux** [comment] 2016-08-17 09:27
The way images for inline stem macros are handled will be aligned with the way they are handled for blocks when the fix for #11 is merged. We still need to align with the behavior of Asciidoctor Diagram, but at least the path will be handled consistently within this extension.

**Closed** 2016-08-20 01:53 UTC

**Comment by ProgramFan** [comment] 2016-08-20 01:58
I have submitted a fix and it works on sample.adoc. Different values can be assigned to `imagesdir` and `imagesoutdir` in my test. Would you please try 932f0b3 to verify the issue is fixed on your document? @igagis @paulvickers

**Comment by igagis** [comment] 2016-08-21 07:41
@ProgramFan I can only try when you release your fix, so I could install via `gem install`. I'm not really familiar with ruby stuff...
